//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenShot_Grab.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenShot_Grab.Resources.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка захвата изображения!.
        /// </summary>
        internal static string capture_err {
            get {
                return ResourceManager.GetString("capture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буфер обмена не содержит изображение!.
        /// </summary>
        internal static string clipboard_err {
            get {
                return ResourceManager.GetString("clipboard_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка захвата изображения.
        /// </summary>
        internal static string event_capture_err {
            get {
                return ResourceManager.GetString("event_capture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставка изображения из буфера.
        /// </summary>
        internal static string event_clipboard {
            get {
                return ResourceManager.GetString("event_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вставки изображения из буфера.
        /// </summary>
        internal static string event_clipboard_err {
            get {
                return ResourceManager.GetString("event_clipboard_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрытие программы.
        /// </summary>
        internal static string event_close {
            get {
                return ResourceManager.GetString("event_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск редактора изображения.
        /// </summary>
        internal static string event_edit {
            get {
                return ResourceManager.GetString("event_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка запуска редактора.
        /// </summary>
        internal static string event_edit_err {
            get {
                return ResourceManager.GetString("event_edit_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Захвачен скриншот экрана.
        /// </summary>
        internal static string event_grab {
            get {
                return ResourceManager.GetString("event_grab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Захвачен скришот части экрана.
        /// </summary>
        internal static string event_grabc {
            get {
                return ResourceManager.GetString("event_grabc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Захвачен скриншот программы.
        /// </summary>
        internal static string event_grabw {
            get {
                return ResourceManager.GetString("event_grabw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление файла.
        /// </summary>
        internal static string event_removefile {
            get {
                return ResourceManager.GetString("event_removefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении файла.
        /// </summary>
        internal static string event_removefile_err {
            get {
                return ResourceManager.GetString("event_removefile_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление изображения.
        /// </summary>
        internal static string event_removeimg {
            get {
                return ResourceManager.GetString("event_removeimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении изображения.
        /// </summary>
        internal static string event_removeimg_err {
            get {
                return ResourceManager.GetString("event_removeimg_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение файла.
        /// </summary>
        internal static string event_save {
            get {
                return ResourceManager.GetString("event_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения файла.
        /// </summary>
        internal static string event_save_err {
            get {
                return ResourceManager.GetString("event_save_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запуск программы.
        /// </summary>
        internal static string event_start {
            get {
                return ResourceManager.GetString("event_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка файла на сервер.
        /// </summary>
        internal static string event_upload {
            get {
                return ResourceManager.GetString("event_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки файла на сервер.
        /// </summary>
        internal static string event_upload_err {
            get {
                return ResourceManager.GetString("event_upload_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка сохранения файла..
        /// </summary>
        internal static string file_err {
            get {
                return ResourceManager.GetString("file_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден!.
        /// </summary>
        internal static string file_nf {
            get {
                return ResourceManager.GetString("file_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть.
        /// </summary>
        internal static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка удаления изображения..
        /// </summary>
        internal static string img_rm_err {
            get {
                return ResourceManager.GetString("img_rm_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязать аккаунт.
        /// </summary>
        internal static string link_acc {
            get {
                return ResourceManager.GetString("link_acc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на активна,.
        /// </summary>
        internal static string link_acc_status {
            get {
                return ResourceManager.GetString("link_acc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на отсуствует..
        /// </summary>
        internal static string noacc {
            get {
                return ResourceManager.GetString("noacc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат не содержит изображение!.
        /// </summary>
        internal static string noprtscr {
            get {
                return ResourceManager.GetString("noprtscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь не найден!.
        /// </summary>
        internal static string path_nf {
            get {
                return ResourceManager.GetString("path_nf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другая копия программы уже открыта!.
        /// </summary>
        internal static string running {
            get {
                return ResourceManager.GetString("running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Серверная ошибка..
        /// </summary>
        internal static string sv_err {
            get {
                return ResourceManager.GetString("sv_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отвязать аккаунт.
        /// </summary>
        internal static string unlink_acc {
            get {
                return ResourceManager.GetString("unlink_acc", resourceCulture);
            }
        }
    }
}
